/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'dessert' : null } |
  { 'breakfast' : null } |
  { 'lunch' : null } |
  { 'snack' : null } |
  { 'dinner' : null };
export interface ChatMessage {
  'sender' : string,
  'message' : string,
  'timestamp' : Time,
}
export type Difficulty = { 'easy' : null } |
  { 'hard' : null } |
  { 'medium' : null };
export interface Recipe {
  'cookingTime' : bigint,
  'difficulty' : Difficulty,
  'name' : string,
  'steps' : Array<string>,
  'category' : Category,
  'ingredients' : Array<string>,
}
export interface RecipeMatch { 'matchPercentage' : bigint, 'recipe' : Recipe }
export type Time = bigint;
export interface _SERVICE {
  'addRecipe' : ActorMethod<
    [string, Array<string>, Array<string>, Category, bigint, Difficulty],
    undefined
  >,
  'getChatHistory' : ActorMethod<[string], Array<ChatMessage>>,
  'getRecipe' : ActorMethod<[string], Recipe>,
  'getRecipesByCategory' : ActorMethod<[Category], Array<Recipe>>,
  'getSuggestionsByIngredients' : ActorMethod<
    [Array<string>],
    Array<RecipeMatch>
  >,
  'searchRecipes' : ActorMethod<[string], Array<Recipe>>,
  'sendMessage' : ActorMethod<[string, string, string], string>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];