/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Category = IDL.Variant({
  'dessert' : IDL.Null,
  'breakfast' : IDL.Null,
  'lunch' : IDL.Null,
  'snack' : IDL.Null,
  'dinner' : IDL.Null,
});
export const Difficulty = IDL.Variant({
  'easy' : IDL.Null,
  'hard' : IDL.Null,
  'medium' : IDL.Null,
});
export const Time = IDL.Int;
export const ChatMessage = IDL.Record({
  'sender' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const Recipe = IDL.Record({
  'cookingTime' : IDL.Nat,
  'difficulty' : Difficulty,
  'name' : IDL.Text,
  'steps' : IDL.Vec(IDL.Text),
  'category' : Category,
  'ingredients' : IDL.Vec(IDL.Text),
});
export const RecipeMatch = IDL.Record({
  'matchPercentage' : IDL.Nat,
  'recipe' : Recipe,
});

export const idlService = IDL.Service({
  'addRecipe' : IDL.Func(
      [
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
        Category,
        IDL.Nat,
        Difficulty,
      ],
      [],
      [],
    ),
  'getChatHistory' : IDL.Func([IDL.Text], [IDL.Vec(ChatMessage)], ['query']),
  'getRecipe' : IDL.Func([IDL.Text], [Recipe], ['query']),
  'getRecipesByCategory' : IDL.Func([Category], [IDL.Vec(Recipe)], ['query']),
  'getSuggestionsByIngredients' : IDL.Func(
      [IDL.Vec(IDL.Text)],
      [IDL.Vec(RecipeMatch)],
      ['query'],
    ),
  'searchRecipes' : IDL.Func([IDL.Text], [IDL.Vec(Recipe)], ['query']),
  'sendMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Category = IDL.Variant({
    'dessert' : IDL.Null,
    'breakfast' : IDL.Null,
    'lunch' : IDL.Null,
    'snack' : IDL.Null,
    'dinner' : IDL.Null,
  });
  const Difficulty = IDL.Variant({
    'easy' : IDL.Null,
    'hard' : IDL.Null,
    'medium' : IDL.Null,
  });
  const Time = IDL.Int;
  const ChatMessage = IDL.Record({
    'sender' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const Recipe = IDL.Record({
    'cookingTime' : IDL.Nat,
    'difficulty' : Difficulty,
    'name' : IDL.Text,
    'steps' : IDL.Vec(IDL.Text),
    'category' : Category,
    'ingredients' : IDL.Vec(IDL.Text),
  });
  const RecipeMatch = IDL.Record({
    'matchPercentage' : IDL.Nat,
    'recipe' : Recipe,
  });
  
  return IDL.Service({
    'addRecipe' : IDL.Func(
        [
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
          Category,
          IDL.Nat,
          Difficulty,
        ],
        [],
        [],
      ),
    'getChatHistory' : IDL.Func([IDL.Text], [IDL.Vec(ChatMessage)], ['query']),
    'getRecipe' : IDL.Func([IDL.Text], [Recipe], ['query']),
    'getRecipesByCategory' : IDL.Func([Category], [IDL.Vec(Recipe)], ['query']),
    'getSuggestionsByIngredients' : IDL.Func(
        [IDL.Vec(IDL.Text)],
        [IDL.Vec(RecipeMatch)],
        ['query'],
      ),
    'searchRecipes' : IDL.Func([IDL.Text], [IDL.Vec(Recipe)], ['query']),
    'sendMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
  });
};

export const init = ({ IDL }) => { return []; };