/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ChatMessage {
    sender: string;
    message: string;
    timestamp: Time;
}
export interface RecipeMatch {
    matchPercentage: bigint;
    recipe: Recipe;
}
export interface Recipe {
    cookingTime: bigint;
    difficulty: Difficulty;
    name: string;
    steps: Array<string>;
    category: Category;
    ingredients: Array<string>;
}
export type Time = bigint;
export enum Category {
    dessert = "dessert",
    breakfast = "breakfast",
    lunch = "lunch",
    snack = "snack",
    dinner = "dinner"
}
export enum Difficulty {
    easy = "easy",
    hard = "hard",
    medium = "medium"
}
export interface backendInterface {
    addRecipe(name: string, ingredients: Array<string>, steps: Array<string>, category: Category, cookingTime: bigint, difficulty: Difficulty): Promise<void>;
    getChatHistory(sessionId: string): Promise<Array<ChatMessage>>;
    getRecipe(name: string): Promise<Recipe>;
    getRecipesByCategory(category: Category): Promise<Array<Recipe>>;
    getSuggestionsByIngredients(availableIngredients: Array<string>): Promise<Array<RecipeMatch>>;
    searchRecipes(searchText: string): Promise<Array<Recipe>>;
    sendMessage(sessionId: string, sender: string, message: string): Promise<string>;
}
import type { Category as _Category, Difficulty as _Difficulty, Recipe as _Recipe, RecipeMatch as _RecipeMatch } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addRecipe(arg0: string, arg1: Array<string>, arg2: Array<string>, arg3: Category, arg4: bigint, arg5: Difficulty): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addRecipe(arg0, arg1, arg2, to_candid_Category_n1(this._uploadFile, this._downloadFile, arg3), arg4, to_candid_Difficulty_n3(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addRecipe(arg0, arg1, arg2, to_candid_Category_n1(this._uploadFile, this._downloadFile, arg3), arg4, to_candid_Difficulty_n3(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async getChatHistory(arg0: string): Promise<Array<ChatMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChatHistory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChatHistory(arg0);
            return result;
        }
    }
    async getRecipe(arg0: string): Promise<Recipe> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecipe(arg0);
                return from_candid_Recipe_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecipe(arg0);
            return from_candid_Recipe_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRecipesByCategory(arg0: Category): Promise<Array<Recipe>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecipesByCategory(to_candid_Category_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecipesByCategory(to_candid_Category_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSuggestionsByIngredients(arg0: Array<string>): Promise<Array<RecipeMatch>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSuggestionsByIngredients(arg0);
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSuggestionsByIngredients(arg0);
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchRecipes(arg0: string): Promise<Array<Recipe>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchRecipes(arg0);
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchRecipes(arg0);
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async sendMessage(arg0: string, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessage(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessage(arg0, arg1, arg2);
            return result;
        }
    }
}
function from_candid_Category_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_Difficulty_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Difficulty): Difficulty {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_RecipeMatch_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RecipeMatch): RecipeMatch {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_Recipe_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Recipe): Recipe {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    matchPercentage: bigint;
    recipe: _Recipe;
}): {
    matchPercentage: bigint;
    recipe: Recipe;
} {
    return {
        matchPercentage: value.matchPercentage,
        recipe: from_candid_Recipe_n5(_uploadFile, _downloadFile, value.recipe)
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cookingTime: bigint;
    difficulty: _Difficulty;
    name: string;
    steps: Array<string>;
    category: _Category;
    ingredients: Array<string>;
}): {
    cookingTime: bigint;
    difficulty: Difficulty;
    name: string;
    steps: Array<string>;
    category: Category;
    ingredients: Array<string>;
} {
    return {
        cookingTime: value.cookingTime,
        difficulty: from_candid_Difficulty_n7(_uploadFile, _downloadFile, value.difficulty),
        name: value.name,
        steps: value.steps,
        category: from_candid_Category_n9(_uploadFile, _downloadFile, value.category),
        ingredients: value.ingredients
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    dessert: null;
} | {
    breakfast: null;
} | {
    lunch: null;
} | {
    snack: null;
} | {
    dinner: null;
}): Category {
    return "dessert" in value ? Category.dessert : "breakfast" in value ? Category.breakfast : "lunch" in value ? Category.lunch : "snack" in value ? Category.snack : "dinner" in value ? Category.dinner : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    easy: null;
} | {
    hard: null;
} | {
    medium: null;
}): Difficulty {
    return "easy" in value ? Difficulty.easy : "hard" in value ? Difficulty.hard : "medium" in value ? Difficulty.medium : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Recipe>): Array<Recipe> {
    return value.map((x)=>from_candid_Recipe_n5(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RecipeMatch>): Array<RecipeMatch> {
    return value.map((x)=>from_candid_RecipeMatch_n13(_uploadFile, _downloadFile, x));
}
function to_candid_Category_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_Difficulty_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Difficulty): _Difficulty {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): {
    dessert: null;
} | {
    breakfast: null;
} | {
    lunch: null;
} | {
    snack: null;
} | {
    dinner: null;
} {
    return value == Category.dessert ? {
        dessert: null
    } : value == Category.breakfast ? {
        breakfast: null
    } : value == Category.lunch ? {
        lunch: null
    } : value == Category.snack ? {
        snack: null
    } : value == Category.dinner ? {
        dinner: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Difficulty): {
    easy: null;
} | {
    hard: null;
} | {
    medium: null;
} {
    return value == Difficulty.easy ? {
        easy: null
    } : value == Difficulty.hard ? {
        hard: null
    } : value == Difficulty.medium ? {
        medium: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
